project:
  type: website
  output-dir: _site

  resources:
    - images/**
    - CNAME


website:
  title: "Observatório da Formação do Sanitarista"
  description: "Painel da Formação do Sanitarista no Brasil"

  site-url: https://painel-da-paula.com

  favicon: images/logo_painel.png

  navbar:
    logo: images/logo_painel.png
    title: false

    left:
      - href: index.qmd
        text: Início

      - href: "#sobre"
        text: Apresentação

      - href: "#objetivo"
        text: Objetivo

      - href: "#indicadores"
        text: Indicadores

      - href: "#dashboard"
        text: Painel da Formação

      - href: "#biblioteca"
        text: Biblioteca

      - href: "#quem-somos"
        text: Quem Somos

    right:
      - text: "Painel Interativo ↗"
        href: "#dashboard"


  page-footer:

    background: "#011a36"

    left: |
      ![](images/ufes.png){width=40%}

    center: |
       ![](images/programa.jpg){width=60%}

    right: |
      ![](images/FAPES.png){width=90%}


format:

  html:
    theme: flatly
    css: styles.css
    toc: false
    email-obfuscation: javascript
    page-layout: full